# https://starship.rs/config

scan_timeout=150
command_timeout=150
add_newline = true

[aws]
disabled = true

[status]
disabled = false

[cmd_duration]
disabled = false

[directory]
truncation_length = 8
truncate_to_repo = false

[dotnet]
disabled = true

[nix_shell]
disabled = true
