#!/usr/bin/env bash

# misc aliases
alias d=docker
alias h='history | rg -i'
alias less='less -R'

# cd
alias po=popd
alias pu=pushd
alias cd=pushd

# ls
alias ls='ls --color=tty'
alias l='ls -l'
alias ll='ls -al'
alias lh='ls -lh'

# git
if [[ "$OSTYPE" == "darwin"* ]]; then
    : # do nothing; the files below don't work
elif [[ -f "/usr/share/bash-completion/completions/git" ]]; then
    source "/usr/share/bash-completion/completions/git"
elif [[ -f "$HOME/completions/git" ]]; then
    # git-bash doesn't have the above git completions file so I copied it from Linux
    source "$HOME/completions/git"
fi

# Git aliases
alias g=git
alias ga='git add'
alias gb='git branch'
alias gc='git commit -v'
alias ggc='git -c commit.gpgsign=false commit -v'
alias gcl='git config --list'
alias gco='git checkout'
alias gpp='git pull --prune'
alias gnp='git --no-pager'
alias gst='git status -sb'
alias gl='git lola'

## Git diff aliases
    # https://stackoverflow.com/a/41730200
    alias gt='git difftool --diff-filter=M'
    alias gts='git difftool --diff-filter=M --staged'

    alias gta='git difftool'
    alias gtsa='git difftool --staged'
    alias gd='git diff'
    alias gds='git diff --staged'

# Git completion for aliases
if type -t __git_complete >&/dev/null ; then
     __git_complete g __git_main
     __git_complete gb _git_branch
     __git_complete gco _git_checkout
     __git_complete gt _git_difftool
     __git_complete gts _git_difftool
     __git_complete gd _git_diff
     __git_complete gds _git_diff
     __git_complete tig _git_branch
 fi

if command -v fzf &>/dev/null ; then
    # inspired by https://news.ycombinator.com/item?id=32106770
    function navigate() {
        local dir;

        echo "Ctrl-D: change directory; Ctrl-C: exit"
        while true; do
            # exit with ^D
            dir="$(ls -a1p | rg '/$' | rg -v '^./$' | fzf --height 40% --reverse --no-multi --preview 'pwd' --preview-window=up,1,border-none --no-info)"
            if [[ -z "${dir}" ]]; then
                break
            else
                pushd "${dir}"
            fi
      done
    }
    alias n=navigate

    # https://news.ycombinator.com/item?id=32107654
    function preview_file() {
        fzf --preview='less {}' --bind shift-up:preview-page-up,shift-down:preview-page-down
    }
    alias pf="preview_file #"

    # https://news.ycombinator.com/item?id=32109120
    function preview_git_commits () {
        git log --oneline --decorate --color | \
            fzf --ansi --preview 'git show $(echo {} | cut -d" " -f1)' \
            --bind shift-up:preview-page-up,shift-down:preview-page-down
    }
    alias pg=preview_git_commits
fi

# Fixup gitconfig
case "$OSTYPE" in
    darwin*)
        CONFIG="$HOME/.dotfiles/gitconfig-osx"
    ;;

    linux*)
        if [[ $(uname -r) =~ icrosoft ]]; then
            CONFIG="$HOME/.dotfiles/gitconfig-windows"
        else
            CONFIG="$HOME/.dotfiles/gitconfig-linux"
        fi
    ;;

    msys*|cygwin*)
        CONFIG="$HOME/.dotfiles/gitconfig-windows"
    ;;

    *)
        echo "Unknown OS: $MY_OSTYPE"
        return
    ;;
esac
ln -sf "$CONFIG" "$HOME/.dotfiles/gitconfig-local"
